name: 'Deploy to S3'
description: 'Deploy to S3'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  region:
    description: 'S3 bucket region'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Folder to deploy'
    required: true
outputs:
  website-url:
    description: 'Website URL'