name: Reusable Workflow
on: 
  workflow_call:
    inputs:
        artifact_name:
            required: true
            type: string
            description: The name of the artifact to download.
    secrets:
        MY_GITHUB_TOKEN:
            required: true
            description: The GitHub token to use for authentication.
    outputs:
        result:
            description: The result of the workflow.
            value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
        outcome: ${{ steps.result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls -al
      - name: Output event data
        run: echo "All good"
      - name: Show token
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}"
      - name: Set output
        id: result
        run: echo "step-result=success" >> $GITHUB_OUTPUT


