name: Reusable Workflow
on: 
  workflow_call:
    inputs:
        artifact_name:
            required: true
            type: string
            description: The name of the artifact to download.
    secrets:
        GITHUB_TOKEN:
            required: true
            description: The GitHub token to use for authentication.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List files
        run: ls -al
      - name: Output event data
        run: echo "All good"
      - name: Show token
        run: echo "${{ secrets.GITHUB_TOKEN }}"
